const ACTIONS = {
  FETCH_ASSETS: 'FETCH_ASSETS',
  FETCH_ASSETS_BY_ID:'FETCH_ASSETS_BY_ID',
  CREATE_ASSETS:'CREATE_ASSETS',
  UPDATE_ASSETS:'UPDATE_ASSETS',
  DELETE_ASSETS:'DELETE_ASSETS',
}
export default ACTIONS
